<?php
/*
 *  Extract parameters from the URL;
*/
if (arg(1) == 'lake-mendota') $GLOBALS['lakeid'] = 'ME';
if (arg(1) == 'lake-monona') $GLOBALS['lakeid'] = 'MO';
if (arg(1) == 'lake-wingra') $GLOBALS['lakeid'] = 'WI';
if (arg(1) == 'fish-lake') $GLOBALS['lakeid'] = 'FI';
if (arg(1) == 'trout-lake') $GLOBALS['lakeid'] = 'TR';
if (arg(1) == 'sparkling-lake') $GLOBALS['lakeid'] = 'SP';
if (arg(1) == 'crystal-lake') $GLOBALS['lakeid'] = 'CR';
if (arg(1) == 'trout-bog') $GLOBALS['lakeid'] = 'TB'; 
if (arg(1) == 'allequash-lake') $GLOBALS['lakeid'] = 'AL';
if (arg(1) == 'big-muskellunge-lake') $GLOBALS['lakeid'] = 'BM';
if (arg(1) == 'crystal-bog') $GLOBALS['lakeid'] = 'CB';
	
/*
 *  Implements hook_block_info();
*/
function lake_longterm_zoom_block_info() {
  //$blocks = array();
  $blocks['lakelt_block'] = array(
    'info' => t('Lake Long-Term'),
    'status' => TRUE,
    'region' => 'sidebar_first',
  );
  return $blocks;
}

/**
 * Implements hook_block_view
 */
function lake_longterm_zoom_block_view() {

//  $block['subject'] = t('Lake Long-Term Data');
  $block['content'] = lake_longterm_zoom_content();
  return $block;
}

function lake_longterm_zoom_content() {

  $lakeid = $GLOBALS['lakeid']; 
  $content = array();
	$macrophytes = array('ME', 'MO', 'WI', 'FI', 'CR', 'TR');
	$phytoplankton = array('ME', 'MO', 'TR', 'CR', 'SP');


  $content['main_block'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_main'),
     ),
  );
  $content['main_block']['title'] = array(
    '#type' => 'markup',
    '#markup' => '<h3>Long-Term Data:</h3>click on icon to explore data',
  );
  $content['main_block']['css_content'] = array(
    '#type' => 'markup',
    '#attached' => array(
      'css' => array(
        drupal_get_path('module','lake_longterm_zoom').'/lake_longterm_zoom.css',
      ),
    ),  
  );



/****************************************************************
              CHEMICAL CONTAINERS
****************************************************************/
//
//Create a main div for chemical limnology
  $content['main_block']['container_chemical'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_chem'),
       'class' => array('lakelt'),
     ),
  );
 //Subcontainer for nitrogen
  $content['main_block']['container_chemical']['chemical_nitrogen'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_n'),
       'class' => array('lakelt_sub'),
     ),
  );
 //Subcontainer for phosphorus
  $content['main_block']['container_chemical']['chemical_phosphorus'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_p'),
       'class' => array('lakelt_sub'),
     ),
  );
 //Subcontainer for doc
  $content['main_block']['container_chemical']['chemical_doc'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_doc'),
      'class' => array('lakelt_sub'),
     ),
  ); 

/****************************************************************
              CHEMICAL CONTENT
****************************************************************/
//Nitrogen
  $n_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/n.jpg',
   'alt' => t('Nitrogen'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_chemical']['chemical_nitrogen']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$n_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/totnuf',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_chemical']['chemical_nitrogen']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Total Nitrogen</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/totnuf',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
//Phosphorus
  $p_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/p.jpg',
   'alt' => t('Phosphorus'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_chemical']['chemical_phosphorus']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$p_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/totpuf',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_chemical']['chemical_phosphorus']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Total Phosphorus</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/totpuf',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
//DOC
  $c_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/c.jpg',
   'alt' => t('Carbon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_chemical']['chemical_doc']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$c_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/doc',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_chemical']['chemical_doc']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Dissolved Organic Carbon</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/doc',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );

/****************************************************************
              BIOLOGY CONTAINERS
****************************************************************/

// 
//Create a main div for biology
  $content['main_block']['container_biology'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_bio'),
       'class' => array('lakelt'),
     ),
  );
/*  $content['main_block']['container_biology']['title'] = array(
    '#type' => 'markup',
    '#markup' => '<h5 class="lakelt_header">Biology</h5>'
  );
  */
 //Subcontainer for fish
  $content['main_block']['container_biology']['biology_fish'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_fish'),
       'class' => array('lakelt_sub'),
     ),
  );

//Subcontainer for macrophytes  
if (in_array($lakeid, $macrophytes)) {
  $content['main_block']['container_biology']['biology_macro'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_macro'),
       'class' => array('lakelt_sub'),
     ),
  );
}
 //Subcontainer for phytoplankton
if (in_array($lakeid, $phytoplankton)) {
  $content['main_block']['container_biology']['biology_phyto'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_phyto'),
       'class' => array('lakelt_sub'),
     ),
  );
}
 //Subcontainer for zooplankton
  $content['main_block']['container_biology']['biology_zoop'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_zoop'),
       'class' => array('lakelt_sub'),
     ),
  );
if ( $lakeid != 'CB') {
 //Subcontainer for chlorophyll
  $content['main_block']['container_biology']['biology_chlor'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_chlor'),
	   'class' => array('lakelt_sub'),
     ),
  );
}
/****************************************************************
              BIOLOGY CONTENT
****************************************************************/

//Fish
  $fish_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/yellowperch.jpg',
   'alt' => t('Fish Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_biology']['biology_fish']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$fish_photo),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/fish',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_biology']['biology_fish']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Fish</p>'),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/fish',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
//Macrophytes
 if ( in_array($lakeid, $macrophytes) ) {
  $macrophyte_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/macrophyteIcon.jpg',
   'alt' => t('Macrophyte Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_biology']['biology_macro']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$macrophyte_photo),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/macro',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_biology']['biology_macro']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Macrophytes</p>'),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/macro',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
 }
//Phytoplankton
if (in_array($lakeid, $phytoplankton)) {
  $phyto_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/diatom3.jpg',
   'alt' => t('Phytoplankton Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_biology']['biology_phyto']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$phyto_photo),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/phyto',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_biology']['biology_phyto']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Phytoplankton</p>'),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/phyto',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
}
//Zooplankton
  $zoop_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/zooplanktonIcon.jpg',
   'alt' => t('Zooplankton Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_biology']['biology_zoop']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$zoop_photo),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/zoop',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );  
  $content['main_block']['container_biology']['biology_zoop']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Zooplankton</p>'),
    '#href' => 'lake-bio-zoom/'.$lakeid.'/zoop',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );  

//Chlorophyll
if ( $lakeid != 'CB') {
  $chlor_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/chlor.jpg',
   'alt' => t('Chlorophyll Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_biology']['biology_chlor']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$chlor_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/chlor',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_biology']['biology_chlor']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Chlorophyll</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/chlor',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
}
  
/****************************************************************
              PHYSICAL CONTAINERS
****************************************************************/
// 
// 
//Create a main div for physical
  $content['main_block']['container_physical'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_phys'),
       'class' => array('lakelt'),
     ),
  );
//Subcontainer for ice cover
if($lakeid != 'FI') {
  $content['main_block']['container_physical']['physical_ice'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_ice'),
	   'class' => array('lakelt_sub'),
     ),
  );
}

 //Subcontainer for water level
if($lakeid != 'WI' && $lakeid != 'FI') {
  $content['main_block']['container_physical']['physical_wlevel'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_wlevel'),
	   'class' => array('lakelt_sub'),
     ),
  );
}
 //Subcontainer for secchi depths
  $content['main_block']['container_physical']['physical_secchi'] = array(
    '#type' => 'container',
    '#attributes' => array(
       'id' => array('lakelt_secchi'),
	   'class' => array('lakelt_sub'),
     ),
  );
/****************************************************************
              PHYSICAL CONTENT
****************************************************************/
  
//Ice Duration
if($lakeid != 'FI') {
  $ice_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/iceIcon.jpg',
   'alt' => t('Ice Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_physical']['physical_ice']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$ice_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/ice_duration',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_physical']['physical_ice']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Ice Duration</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/ice_duration',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
}

if($lakeid != 'WI' && $lakeid != 'FI') {
  //Lake Levels
  $wlevel_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/waterlevelIcon.jpg',
   'alt' => t('Lake Level Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_physical']['physical_wlevel']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$wlevel_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/lake_level',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
  $content['main_block']['container_physical']['physical_wlevel']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Lake Level</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/lake_level',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );
}
  //Secchi Depth
  $secchi_photo = array(
   'path' => drupal_get_path('module','lake_longterm_zoom').'/images/secchiIcon.jpg',
   'alt' => t('Secchi Disk Icon'),
   'attributes' => array('class' => 'lake_photo_icon'),
  );
  $content['main_block']['container_physical']['physical_secchi']['image']['link'] = array(
    '#type' => 'link',
    '#title' => theme('image',$secchi_photo),
    '#href' => '1dPlotzoom/'.$lakeid.'/secchi',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );  
  $content['main_block']['container_physical']['physical_secchi']['label']['link'] = array(
    '#type' => 'link',
    '#title' => t('<p class="lt_label">Secchi Depth</p>'),
    '#href' => '1dPlotzoom/'.$lakeid.'/secchi',
    '#options' => array(
       'attributes' => array(),
       'html' => TRUE,
    ),
  );  

  return $content;
  
}

