//
//  Weather.h
//  Weather Class generated by the Core Data. This class contains the extra method for manipulating the get and set method
//  
//
//  Created by Junjie on 16/1/2.
//  Copyright © 2016年 Junjie. All rights reserved.
//

#import <Foundation/Foundation.h>
#import <CoreData/CoreData.h>

NS_ASSUME_NONNULL_BEGIN

@interface Weather : NSManagedObject

-(NSString *)description;

@end

NS_ASSUME_NONNULL_END

#import "Weather+CoreDataProperties.h"
